# Generated by Django 3.1.8 on 2023-07-05 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('icon', models.ImageField(default=None, upload_to='ach_admin/acheivements')),
            ],
        ),
        migrations.CreateModel(
            name='AchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=None, limit_choices_to={'groups__verbose_name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student with Achievement',
                'verbose_name_plural': 'Students with Achievements',
            },
        ),
        migrations.CreateModel(
            name='FinishedAchievementAchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField(default=datetime.date.today)),
                ('ach_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achstudent')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achievement')),
            ],
            options={
                'verbose_name': 'Finished Achievement',
                'verbose_name_plural': 'Finished Achievements',
            },
        ),
        migrations.CreateModel(
            name='CurrentAchievementAchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField(default=datetime.date.today)),
                ('ach_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achstudent')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achievement')),
            ],
            options={
                'verbose_name': 'Current Achievement',
                'verbose_name_plural': 'Current Achievements',
            },
        ),
        migrations.CreateModel(
            name='AchTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher with Achievement',
                'verbose_name_plural': 'Teacher with Achievements',
            },
        ),
        migrations.CreateModel(
            name='AchievementAchTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField(default=datetime.date.today)),
                ('ach_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achteacher')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ach_admin.achievement')),
            ],
            options={
                'verbose_name': 'Assigned Achievement',
                'verbose_name_plural': 'Assigned Achievements',
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='assigned_coaches',
            field=models.ManyToManyField(blank=True, through='ach_admin.AchievementAchTeacher', to='ach_admin.AchTeacher'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='finished_students',
            field=models.ManyToManyField(blank=True, related_name='finished_students', through='ach_admin.FinishedAchievementAchStudent', to='ach_admin.AchStudent'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='subscribed_students',
            field=models.ManyToManyField(blank=True, through='ach_admin.CurrentAchievementAchStudent', to='ach_admin.AchStudent'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_achievement_title'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(check=models.Q(title__regex='^[a-zA-Z0-9_]+$'), name='achievement_title_format'),
        ),
    ]
