# Generated by Django 3.1.8 on 2023-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='achievement_images')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('club_name', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('assigned_achievements', models.ManyToManyField(to='ach_admin.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('current_achievements', models.ManyToManyField(blank=True, related_name='current_achievements', to='ach_admin.Achievement')),
                ('finished_achievements', models.ManyToManyField(blank=True, related_name='finished_achievements', to='ach_admin.Achievement')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='achievement',
            name='assigned_coaches',
            field=models.ManyToManyField(blank=True, to='ach_admin.Coach'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='finished_students',
            field=models.ManyToManyField(blank=True, related_name='finished_students', to='ach_admin.Student'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='subscribed_students',
            field=models.ManyToManyField(blank=True, to='ach_admin.Student'),
        ),
    ]
