# Generated by Django 3.1.8 on 2023-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', through='ach_admin.AchievementAchStudent', to='ach_admin.AchStudent'),
        ),
    ]
