# Generated by Django 3.1.8 on 2023-07-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ach_admin', '0002_auto_20230705_2135'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='achievement',
            name='unique_achievement_title',
        ),
        migrations.RemoveConstraint(
            model_name='achievement',
            name='achievement_title_format',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='achstudent',
            name='user',
            field=models.OneToOneField(default=None, limit_choices_to={'groups__verbose_name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
