# Generated by Django 3.1.8 on 2023-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0002_achievement_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementachstudent',
            name='status',
            field=models.CharField(choices=[('subscribed', 'Subscribed'), ('finished', 'Finished')], max_length=20),
        ),
    ]
