# Generated by Django 3.1.8 on 2023-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0002_auto_20230705_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='assigned_coaches',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='ach_admin.AchTeacher'),
        ),
    ]
