# Generated by Django 3.1.8 on 2023-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0003_auto_20230705_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
