# Generated by Django 3.1.8 on 2023-07-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0003_auto_20230708_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementachteacher',
            old_name='date_achieved',
            new_name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='finished_students',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='subscribed_students',
        ),
    ]
