# Generated by Django 3.1.8 on 2023-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0003_auto_20230705_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='assigned_coaches',
            field=models.ManyToManyField(blank=True, through='ach_admin.AchievementAchTeacher', to='ach_admin.AchTeacher'),
        ),
    ]
