# Generated by Django 3.1.8 on 2023-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0004_auto_20230621_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_achievements',
            field=models.ManyToManyField(blank=True, to='ach_admin.Achievement'),
        ),
    ]
