# Generated by Django 3.1.8 on 2023-06-28 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ach_admin', '0008_auto_20230622_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='AchStudent',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='AchTeacher',
        ),
    ]
