# Generated by Django 3.1.8 on 2023-06-28 22:13

import ach_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0009_auto_20230628_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to=ach_admin.models.get_achievement_icon_path),
        ),
    ]
