# Generated by Django 3.1.8 on 2023-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0012_auto_20230630_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to='achievements'),
        ),
    ]
