# Generated by Django 3.1.8 on 2023-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0013_auto_20230630_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(default=None, upload_to='acheivements'),
        ),
    ]
