# Generated by Django 3.1.8 on 2023-06-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ach_admin', '0014_auto_20230630_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(default=None, upload_to='ach_admin/acheivements'),
        ),
    ]
